### PR TITLE
Added Last Updated and Contributors List per page

### PR DESCRIPTION
**Pull request by Fir121**
Solves #83.

Have confirmed it works in github pages deployment at [personal deployment](https://fir121.github.io/Uni_Notes/)
Will have to check if it works in netlify. Hopefully preview build gives some clarity.

As seen at the deployment above, it adds the details at the bottom of the page. There will be no changes to page load speed or performances since it is a static feature added during each build.

### CODE REVIEW

**Comment by AhmedThahir** [comment]
Looks great!!! Amazing job.

**Comment by AhmedThahir** [comment]
I was thinking it'd be better to put the details at the top of the page, just below the title. What do you think?

**Comment by AhmedThahir** [comment]
Also, is it possible to put the link of author as GitHub profile link rather than email? This would be better as 1) I don't want to encourage people to send authors mass mail, 2) increases reach of authors' GitHub pages

I tried to look it up, but couldn't find anything.

**Comment by AhmedThahir** [comment]
I observed that you have hidden authors from home page; great choice. It would be better to exclude date info from home page as well. 

```
exclude:
          - index.md
```

**Comment by Fir121** [comment]
Putting it on top will mean it appears above the header, if that's ok I can try it

**Comment by AhmedThahir** [comment]
> Putting it on top will mean it appears above the header, if that's ok I can try it


No, that's not okay. Is there no easy way to put it below the page title? Just try and lemme know.

**Comment by Fir121** [comment]
Have done the GitHub link as well as exclude (locally). Will push as soon as my PR with [this new plugin](https://github.com/ojacques/mkdocs-git-committers-plugin-2) is approved.

I'm not able to figure out a non JavaScript way to put the content below the title, without editing each file which is of course a bad idea. Let me know if you find any reference online or have any ideas on how to do it.

This PR might need to be open for a bit because the exclude feature will be added to pip only after my [PR](https://github.com/ojacques/mkdocs-git-committers-plugin-2/pull/31) is approved.

**Comment by AhmedThahir** [comment]
Damn dude you're a genius!!!

**Comment by AhmedThahir** [comment]
I believe it would be better to have time details in `timeago` format. That is more intuitive than exact date.

**Comment by Fir121** [comment]
> You may rebass and merge for now (since the commits you've made using the other package might come in handy for future reference), and then we can exclude once your PR gets approved.

Let's hold off for a week, no clue how active the plugin maintainers are. After that will merge.

**Comment by Fir121** [comment]
Ready for merge @AhmedThahir

**Comment by AhmedThahir** [comment]
Great work!

**Comment by AhmedThahir** [comment]
I just observed that it's not in `timeago` format, is this a mistake or do you prefer the regular date format?

**Comment by Fir121** [comment]
It is in timeago format for me?

image

**Comment by AhmedThahir** [comment]
No no, alright see:

```
November 28, 2019           # type: date (default)
November 28, 2019 13:57:28  # type: datetime
2019-11-28                  # type: iso_date
2019-11-28 13:57:26         # type: iso_datetime
20 hours ago                # type: timeago
28. November 2019           # type: custom
29
```

Options

```
plugins:
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: true
      strict: true
```

Reference: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/

**Comment by AhmedThahir** [comment]
> image

Also, last update feels odd grammatically. I feel one of the following would be better. 

- Last updated
- Latest update

Just verify if what I'm saying make sense and proceed with whichever feels correct, I trust you lmao.

**Comment by Fir121** [comment]
Aah I had thought you meant the normal format, but yeah this is better

PS: I kept reading time ago as timeago (like trivago) 🙈

Will make a PR soon

**Comment by AhmedThahir** [comment]
What you saying trivago and all 😭😭

**Comment by AhmedThahir** [comment]
> Is there no easy way to put it below the page title?

## My Logic
1. Find the first h1 element using javascript queryselector
2. User javascript insertAfter 

## Screenshots

As you can see, first element is always h1

### Page with a h1 in the markdown file 
image

### Page without a h1 in the markdown file 
image

**Pull request merged**
