### PR TITLE
Ysh1th patch 2 1

### PR DESCRIPTION
**Pull request by ysh1th**

### CODE REVIEW

**Comment by ysh1th** [comment]
Ok. will add additional instructions

**Comment by ysh1th** [comment]
Done with the updates. ✌️

**Comment by AhmedThahir** [comment]
Verify again. I think you are getting confused with the online contributions.

```
On the text field for the file name, first write the course name you want to introduce.
Then type /. This creates a new folder.
```

Refer to the original guidelines

https://uni-notes.netlify.app/CONTRIBUTING/#guidelines

Also, ensure that all the points that I told Krish and tagged you in are also there.

**Comment by AhmedThahir** [comment]
What's the update?

**Comment by ysh1th** [comment]
On it

**Comment by ysh1th** [comment]
@AhmedThahir done with updating the steps to contribute through local machine, in elaborate.
pls check if anything is missing and is good to go.

**Review by AhmedThahir — APPROVED** [review]

**Pull request merged**
