### PR TITLE
Change date format, grammar

### PR DESCRIPTION
**Pull request by Fir121**
Addresses the issue brought up in #87 after merge.

[Preview](https://fir121.github.io/Uni_Notes/)

### CODE REVIEW

**Comment by AhmedThahir** [comment]
Just keep the horizontal separator above this, like how you did before.

**Comment by Fir121** [comment]
Hm strange, I think that was automatically added last time. Anyway have done so now.

**Comment by AhmedThahir** [comment]
Looks great! Is there no way to make the contributor's name come instead of profile name?

For eg: Ahmed Thahir instead of AhmedThahir

**Comment by Fir121** [comment]
> Is there no way to make the contributor's name come instead of profile name? For eg: Ahmed Thahir instead of AhmedThahir

Nope, as far as I can tell, this is not possible :(

If people want to find out the contributors name they can always click on it and it will take them to their profile. In a way this is good since not all contributors want their real name, their profile is the safe alternative.

**Pull request merged**
