### PR TITLE
PR #10

### PR DESCRIPTION
**Pull request by SivaaB**
This Pull Request is to add my Java_Notes (very basic) under the School Section. Contains both theory and written code explanations for each concept.

### CODE REVIEW

**Comment by AhmedThahir** [comment]
Looks great!

But OOP already has my advanced notes for Java, which makes this repetitive. My CPP notes are different cuz CPP isn't taught in uni.

Can you please try to find a way to contribute to that folder with your notes: https://uni-notes.netlify.app/2_Core/Object_Oriented_Programming/01_Intro

**Comment by SivaaB** [comment]
You're correct Thahir, and yes I could potentially find a way to incorporate mine into yours. 

But, Just like how you had C in your time at CBSE and now we have Python at CBSE. Java is being taught in all ICSE/IGCSE schools compulsorily as a part of their coursework. Just like how you had C in your time at CBSE and now we have Python at CBSE. From that point of view, this is meant to serve as an intro to the more elaborate coursework being taught at university. 

At any rate if you still find this repetitive then no worries. I will do the needful. Just wanted to put my counter - point across.

**Comment by AhmedThahir** [comment]
Ah yes, I forgot to mention this (I said it in my head 😭)

After combining your notes with my OOPS intro, you could move it to grade 12 folder.

Then on the OOPS intro file, add a link to the grade 12 java file.

**Comment by AhmedThahir** [comment]
Pls change the names of the files into something meaningful

01_Topic1.md
02_Topic2.md
...

**Comment by AhmedThahir** [comment]
Any updates?

**Comment by SivaaB** [comment]
Hands full at the moment, ignore the new commit. Will make amends once we are nearing Compre szn, I'll have more topics to add + will be able to give more structure with the naming.

**Comment by AhmedThahir** [comment]
No issues!

Closing this for now. Please re-open when required.

**Pull request closed without merging**
