### PR TITLE
PR For bug fixes and Feature Addition

### PR DESCRIPTION
**Pull request by Fir121**
3 Changes made in this PR

1. Changed an image filename - this was causing an issue in Windows during git clone. Filename was too long.
2. Fixed the GIT COMMITTERS PLUGIN error, to be fixed on netlify (will guide through the steps, after this PR is deployed) #111 
3. Added giscus commenting async, lazy loaded. #61

### CODE REVIEW

**Comment by Fir121** [comment]
As you can see in the deploy preview log, this issue exists

image

refer the below for the fix
1. https://github.com/ojacques/mkdocs-git-committers-plugin-2?tab=readme-ov-file#setup
2. https://docs.netlify.com/environment-variables/get-started/

**Comment by AhmedThahir** [comment]
I'm assuming giscus matches the page name and issue name. So, if we rename a page, renaming the discussion would still retrieve the comments for that page.

Is this correct?

**Comment by AhmedThahir** [comment]
> Since netlify.toml is stored in your repository, we recommend setting sensitive values with the [Netlify UI, CLI, or API](https://docs.netlify.com/environment-variables/get-started/#create-variables-with-the-netlify-ui-cli-or-api) instead, where possible.

Can you tell what exactly should be the name & value of the environment variable?

**Comment by AhmedThahir** [comment]
Everything looks good in terms of the ui of the comments section.

The only thing is that the git-commiters section doesn't look nice there. We need to move it to the top.

I have sent a suggestion for it. Lemme know if that is feasible, and I can try to do it myself since you've already done a lot.

**Comment by Fir121** [comment]
> I'm assuming giscus matches the page name and issue name. So, if we rename a page, renaming the discussion would still retrieve the comments for that page.

Giscus will check [discussions>comments](https://github.com/uni-notes/uni-notes/discussions/categories/comments) for an exact match for the page title, if it is not present, it will create a new discussion. I realize now this can create an issue if there are duplicate titles (dunno if that happens). I can change it to pathname, what do you think?

And yes if title is changed, the discussion will change - we can resolve this by editing the discussion title if a document title is ever changed. Same for pathname if we use that.

image

**Comment by Fir121** [comment]
> Can you tell what exactly should be the name & value of the environment variable?

MKDOCS_GIT_COMMITTERS_APIKEY

value is given by token created in GitHub.

> The token does not need any scope: uncheck everything when creating the GitHub Token at [github.com/settings/personal-access-tokens/new](https://github.com/settings/personal-access-tokens/new), unless you access private repositories.

[Reference](https://github.com/ojacques/mkdocs-git-committers-plugin-2?tab=readme-ov-file#setup)

**Comment by Fir121** [comment]
> I have sent a suggestion for it.

Yeah I remember seeing that somewhere, below the header tag right? Can you link that here so I can recall.

**Comment by AhmedThahir** [comment]
> > I have sent a suggestion for it.
> 
> Yeah I remember seeing that somewhere, below the header tag right? Can you link that here so I can recall.

https://github.com/uni-notes/uni-notes/pull/87#issuecomment-1929942867

**Comment by AhmedThahir** [comment]
> And yes if title is changed, the discussion will change - we can resolve this by editing the discussion title if a document title is ever changed. Same for pathname if we use that.

Yes, I agree with this would be better approach.

**Comment by AhmedThahir** [comment]
> > Can you tell what exactly should be the name & value of the environment variable?
> 
> MKDOCS_GIT_COMMITTERS_APIKEY
> 
> value is given by token created in GitHub.
> 
> > The token does not need any scope: uncheck everything when creating the GitHub Token at [github.com/settings/personal-access-tokens/new](https://github.com/settings/personal-access-tokens/new), unless you access private repositories.
> 
> [Reference](https://github.com/ojacques/mkdocs-git-committers-plugin-2?tab=readme-ov-file#setup)

Just for documentation, I'm sending here. @Fir121 & I had this convo on WhatsApp

**Thahir**
image

Since it's only read-only, why don't we directly put it on the netlify.toml?

**Firas**
No exposing any token is never a good idea maybe the rate limit could be abused by hackers or something
Chances are GitHub themselves will invalidate the token

**Thahir**

image

**Comment by AhmedThahir** [comment]
Preview not appearing due to https://github.com/uni-notes/uni-notes/issues/123

**Comment by Fir121** [comment]
Personal preview: https://fir121.github.io/uni-notes/

**Comment by AhmedThahir** [comment]
Looks great!

image

**Comment by AhmedThahir** [comment]
@Fir121, what do you think of this instead?

image

**Comment by Fir121** [comment]
> @Fir121, what do you think of this instead?

Saw it already, LGTM 👍

**Review by AhmedThahir — APPROVED** [review]
If you dislike my changes, you may revert my commits.

Either way, feel free to merge.

**Comment by AhmedThahir** [comment]
Great job!

**Pull request merged**
