### PR TITLE
removed `{ loading=lazy }` mentioned after er.svg

### PR DESCRIPTION
**Pull request by ysh1th**

### CODE REVIEW

**Comment by AhmedThahir** [comment]
Loading = lazy is important for optimizing load performance. Kindly reverse this commit.

**Comment by AhmedThahir** [comment]
Oh nvm ... you didn't merge it, right? my bad

**Comment by ysh1th** [comment]
I wasn’t sure about its use so created pull request.

**Comment by AhmedThahir** [comment]
Ah no issues!
In future just create an issue instead if you're unsure.

**Comment by ysh1th** [comment]
Sure

**Pull request closed without merging**
