### PR TITLE
PR6

### PR DESCRIPTION
**Pull request by SivaaB**
This PR is addressing Issue #32 and points discussed in #43 

As suggested came up w a very basic `contributing_guidelines.md` file, please go over it and let me know if it requires any change -- I think it should be good for now. We can add content as we move forward.

### CODE REVIEW

**Review by AhmedThahir — CHANGES_REQUESTED** [review]
Just verify my commits for the contribution guidelines.

- Added an example equation
- Use pure markdown syntax for images. 
- The images will be locally hosted. Don't worry, the updated images will work (it won't appear for you, as they are not yet in your fork).
- Moved the guidelines to the docs folder, so that it appears on the app (we are expecting higher traffic on the app, than GitHub directly). I will add a link to this file in the main readme file, no worries

**Comment by SivaaB** [comment]
Got it, thank you for making those edits.

**Comment by AhmedThahir** [comment]
Shall i merge with the main repo?

**Comment by SivaaB** [comment]
Sure, go ahead.

**Comment by AhmedThahir** [comment]
> Just to clarify, since you've made these edits yourself [assuming you'll merge them too] -- is there anything else you'd like me to add? (it says changes requested, so wanted to clarify)

I just wanted to ensure you're cool with these changes

**Comment by AhmedThahir** [comment]
Good work @SivaaB

**Pull request merged**
